version: '3'

services:
  ps:
    build: ./
    command: ./bin/pyspark
    volumes:
        - .:/app

  psnb:
    build: ./
    command: jupyter notebook --ip 0.0.0.0 --port 8888 --allow-root --no-browser
    volumes:
        - .:/app
    ports:
        - "8888:8888"
